spring.application.name=currency-converter

server.port = 8081


jwt.secret=abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
jwt.expiration=3600000

spring.data.mongodb.uri=mongodb://localhost:27017/currency
